<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GridViewForm1.aspx.cs" Inherits="GridView_Sample.GridViewForm1" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>SqlDataAdapter～DataTable版</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            SqlDataAdapter～DataTable版
        </div>
        <div>
            <asp:GridView ID="GridView" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnPageIndexChanging="GridView_PageIndexChanging" OnRowDataBound="GridView_RowDataBound" OnRowDeleting="GridView_RowDeleting" OnRowEditing="GridView_RowEditing" OnSelectedIndexChanged="GridView_SelectedIndexChanged" OnSelectedIndexChanging="GridView_SelectedIndexChanging" OnSorting="GridView_Sorting"></asp:GridView>
        </div>
        <div>
            発生したイベント：<asp:Literal ID="Literal_Event" runat="server"></asp:Literal><br />
            イベントの引数など：<asp:Literal ID="Literal_Args" runat="server"></asp:Literal>
        </div>
        <div>
            <a href="GridViewForm0.aspx">SqlDataSource版（GridViewForm0.aspx）</a><br />
            <a href="GridViewForm2.aspx">DAO/DTO版（AutoGenerateColumn=True）（GridViewForm2.aspx）</a><br />
            <a href="GridViewForm3.aspx">DAO/DTO版（AutoGenerateColumn=False）（GridViewForm3.aspx）</a>
        </div>
    </form>
</body>
</html>