<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GridViewForm3.aspx.cs" Inherits="GridView_Sample.GridViewForm3" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>DAO/DTO版（AutoGenerateColumns=False）</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            DAO/DTO版（AutoGenerateColumns=False）
        </div>
        <div>
            <asp:GridView ID="GridView" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnPageIndexChanging="GridView_PageIndexChanging" OnRowDataBound="GridView_RowDataBound" OnRowDeleting="GridView_RowDeleting" OnRowEditing="GridView_RowEditing" OnSelectedIndexChanged="GridView_SelectedIndexChanged" OnSelectedIndexChanging="GridView_SelectedIndexChanging" OnSorting="GridView_Sorting">
                <Columns>
                    <asp:BoundField DataField="StaffId" HeaderText="スタッフID" SortExpression="StaffId" />
                    <asp:BoundField DataField="Account" HeaderText="アカウント" SortExpression="Account" />
                    <asp:BoundField DataField="Password" HeaderText="パスワード" SortExpression="Password" />
                    <asp:BoundField DataField="DisplayName" HeaderText="表示名" SortExpression="DisplayName" />
                    <asp:BoundField DataField="StaffType" HeaderText="スタッフ種別" SortExpression="StaffType" />
                    <asp:BoundField DataField="UpdateDate" HeaderText="更新日時" SortExpression="UpdateDate" />
                    <asp:BoundField DataField="UpdateStaffId" HeaderText="更新スタッフID" SortExpression="UpdateStaffId" />
                    <asp:BoundField DataField="DeleteDate" HeaderText="削除日時" SortExpression="DeleteDate" />
                </Columns>
            </asp:GridView>
        </div>
        <div>
            発生したイベント：<asp:Literal ID="Literal_Event" runat="server"></asp:Literal><br />
            イベントの引数など：<asp:Literal ID="Literal_Args" runat="server"></asp:Literal>
        </div>
        <div>
            <a href="GridViewForm0.aspx">SqlDataSource版（GridViewForm0.aspx）</a><br />
            <a href="GridViewForm1.aspx">SqlDataAdapter～DataTable版（GridViewForm1.aspx）</a><br />
            <a href="GridViewForm2.aspx">DAO/DTO版（AutoGenerateColumns=True）（GridViewForm2.aspx）</a>
        </div>
    </form>
</body>
</html>