<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GridViewForm1.aspx.cs" Inherits="GridView_Sample.GridViewForm1" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            
        </div>
        <div>
            <asp:GridView ID="GridView" runat="server" AllowSorting="True" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" OnPageIndexChanging="GridView_PageIndexChanging" OnRowDeleting="GridView_RowDeleting" OnRowEditing="GridView_RowEditing" OnSelectedIndexChanging="GridView_SelectedIndexChanging" OnSorting="GridView_Sorting" OnSelectedIndexChanged="GridView_SelectedIndexChanged" OnRowDataBound="GridView_RowDataBound"></asp:GridView>
        </div>
        <div>
            発生したイベント：<asp:Literal ID="Literal_Event" runat="server"></asp:Literal><br />
            イベントの引数など：<asp:Literal ID="Literal_Args" runat="server"></asp:Literal>
        </div>
    </form>
</body>
</html>