<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GridViewForm4.aspx.cs" Inherits="GridView_Sample.GridViewForm4" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>SqlDataSource版</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            SqlDataSource版
        </div>
        <div>
            <asp:GridView ID="GridView" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="StaffId" DataSourceID="SqlDataSource" OnRowDataBound="GridView_RowDataBound" OnRowDeleting="GridView_RowDeleting" OnRowEditing="GridView_RowEditing" OnSelectedIndexChanged="GridView_SelectedIndexChanged" OnSelectedIndexChanging="GridView_SelectedIndexChanging">
                <Columns>
                    <asp:BoundField DataField="StaffId" HeaderText="StaffId" InsertVisible="False" ReadOnly="True" SortExpression="StaffId" />
                    <asp:BoundField DataField="Account" HeaderText="Account" SortExpression="Account" />
                    <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                    <asp:BoundField DataField="DisplayName" HeaderText="DisplayName" SortExpression="DisplayName" />
                    <asp:BoundField DataField="StaffType" HeaderText="StaffType" SortExpression="StaffType" />
                    <asp:BoundField DataField="UpdateDate" HeaderText="UpdateDate" SortExpression="UpdateDate" />
                    <asp:BoundField DataField="UpdateStaffId" HeaderText="UpdateStaffId" SortExpression="UpdateStaffId" />
                    <asp:BoundField DataField="DeleteDate" HeaderText="DeleteDate" SortExpression="DeleteDate" />
                </Columns>
            </asp:GridView>
        </div>
        <div>
            発生したイベント：<asp:Literal ID="Literal_Event" runat="server"></asp:Literal><br />
            イベントの引数など：<asp:Literal ID="Literal_Args" runat="server"></asp:Literal>
        </div>
        <div>
            <a href="GridViewForm1.aspx">SqlDataAdapter～DataTable版（GridViewForm1.aspx）</a><br />
            <a href="GridViewForm2.aspx">DAO/DTO版（AutoGenerateColumn=True）（GridViewForm2.aspx）</a><br />
            <a href="GridViewForm3.aspx">DAO/DTO版（AutoGenerateColumn=False）（GridViewForm3.aspx）</a>
        </div>
        <asp:SqlDataSource ID="SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ASPNETConnectionString %>" SelectCommand="SELECT [StaffId], [Account], [Password], [DisplayName], [StaffType], [UpdateDate], [UpdateStaffId], [DeleteDate] FROM [Staff]"></asp:SqlDataSource>
    </form>
</body>
</html>